# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'abc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for abc

  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'InstagramKit'

  pod 'Braintree'
  pod 'BraintreeDropIn'
  # comment the next line to disable Apple pay
  pod 'Braintree/Apple-Pay'
  # comment the next line to disable PayPal
  pod 'Braintree/PayPal'
  # comment the next line to disable Venmo
  pod 'Braintree/Venmo'
  # Data collector for Braintree Advanced Fraud Tools
  pod 'Braintree/DataCollector'
  
  # comment the next line to disable credit card scanning
  pod 'CardIO'
  
  pod 'Stripe'

end
